name: Compile, Test, and Deploy
on: [ 'push' ]
env:
  SPRING_DATASOURCE_PASSWORD: ${{secrets.SPRING_DATASOURCE_PASSWORD}}
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Set up JDK17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Set up maven
      uses: stCarolas/setup-maven@v4.3
      with:
        maven-version: 3.8.4
    - name: Run tests
      run: mvn clean verify